import os,glob,shutil

# import root environment
Import( "env", "SGlob" )
myenv = env.Copy()


cpps = SGlob("*.cpp")
pycpps = SGlob("python_*.cpp")
for pf in pycpps: cpps.remove(pf)
print cpps

casalibd = os.path.join(myenv['CASAROOT'],myenv['CASAARCH'],'lib')

# location of libcasav.a
myenv.Prepend( LIBPATH = ['#/build'] )
myenv.Install('#build', os.path.join(casalibd, 'libwcs.a'))
myenv['SHLIBPREFIX']=""   #gets rid of lib prefix

# need to create library here to fool  scons linker
casav = myenv.StaticLibrary(target = "casav", source = os.path.join(casalibd, 'version.o'))
# Finally create the library for the module
so = myenv.SharedLibrary( target = "_asap", source = cpps+pycpps )
Return("so")
